package Lexer;

public enum TokenType {
    WHILE, LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    IDENTIFIER, INTEGER_LITERAL, SEMICOLON, EQUALS, PLUS, MINUS,
    TIMES, DIVIDE, LESS_THAN, GREATER_THAN, AND, OR, NOT, EOF
}
